# Generated by Django 3.1.2 on 2020-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
